name: Create Release

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Verify branch
              run: |
                  if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
                    echo "Not on main branch, exiting."
                    exit 1
                  fi

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false
