name: Simple Status Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a simple check
      run: |
        echo "Running a simple check..."
        # Check if a file exists (as an example condition)
        if [ -f "README.md" ]; then
          echo "README.md exists."
        else
          echo "README.md does not exist."
          exit 1
        fi
